//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SacredUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SacredUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] antqs__ {
            get {
                object obj = ResourceManager.GetObject("antqs__", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AppLicense {
            get {
                object obj = ResourceManager.GetObject("AppLicense", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _LAVA00.tga
        ///_LAVA01.tga
        ///_LAVA02.tga
        ///_LAVA03.tga
        ///_LAVA04.tga
        ///_LAVA05.tga
        ///_LAVA06.tga
        ///_LAVA07.tga
        ///_LAVA08.tga
        ///_LAVA09.tga
        ///_LAVA10.tga
        ///_LAVA11.tga
        ///_LAVA12.tga
        ///_LAVA13.tga
        ///_LAVA14.tga
        ///_LAVA15.tga
        ///_LAVA16.tga
        ///_LAVA17.tga
        ///_LAVA18.tga
        ///_LAVA19.tga
        ///_LAVA20.tga
        ///_LAVA21.tga
        ///_LAVA22.tga
        ///_LAVA23.tga
        ///_LAVA24.tga
        ///_LAVA25.tga
        ///_LAVA26.tga
        ///_LAVA27.tga
        ///_LAVA28.tga
        ///_LAVA29.tga
        ///_LAVA30.tga
        ///_LAVA31.tga
        ///_LAVA32.tga
        ///_LAVA33.tga
        ///_LAVA34.tga
        ///_LAVA35.tga
        ///_LAVA36.tga
        ///_LAVA37.tga
        ///_LAVA38.tga
        ///_LAVA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ar_lava {
            get {
                return ResourceManager.GetString("ar_lava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI_MAIN_01.TGA
        ///GUI_MAIN_02.TGA
        ///GUI_MAIN_03.TGA
        ///GUI_MAIN_12.TGA
        ///GUI_MAIN_13.TGA
        ///GUI_MAIN_05.TGA
        ///GUI_DAYNIGHTALPHA.TGA
        ///GUI_OPTION_BACKGROUND00.TGA
        ///UW_OPTION_1_01.TGA
        ///UW_OPTION_1_02.TGA
        ///UW_OPTION_1_03.TGA
        ///UW_OPTION_1_04.TGA
        ///UW_OPTION_1_05.TGA
        ///UW_OPTION_1_06.TGA
        ///UW_OPTION_1_07.TGA
        ///UW_OPTION_1_08.TGA
        ///UW_OPTION_1_09.TGA
        ///UW_OPTION_1_10.TGA
        ///UW_OPTION_1_11.TGA
        ///UW_OPTION_1_12.TGA
        ///GUI_MAIN_10.TGA
        ///GUI_UW_OPTION1.TGA
        ///GUI_UW_OPTION2.TGA
        ///GUI_UW_OPTION3.TGA
        ///GUI_UW_OPTION4.TGA
        ///GUI_UW_OPTION5.TGA
        ///G [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ar_odtx {
            get {
                return ResourceManager.GetString("ar_odtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _WATER00.tga
        ///_WATER01.tga
        ///_WATER02.tga
        ///_WATER03.tga
        ///_WATER04.tga
        ///_WATER05.tga
        ///_WATER06.tga
        ///_WATER07.tga
        ///_WATER08.tga
        ///_WATER09.tga
        ///_WATER10.tga
        ///_WATER11.tga
        ///_WATER12.tga
        ///_WATER13.tga
        ///_WATER14.tga
        ///_WATER15.tga
        ///_WATER16.tga
        ///_WATER17.tga
        ///_WATER18.tga
        ///_WATER19.tga
        ///_WATER20.tga
        ///_WATER21.tga
        ///_WATER22.tga
        ///_WATER23.tga
        ///_WATER24.tga
        ///_WATER25.tga
        ///_WATER26.tga
        ///_WATER27.tga
        ///_WATER28.tga
        ///_WATER29.tga
        ///_WATER30.tga
        ///_WATER31.tga
        ///_WATER32.tga
        ///_WATER33.tga
        ///_WATER34.tga
        ///_WATER35.tga
        ///_WATER36 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ar_watr {
            get {
                return ResourceManager.GetString("ar_watr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BalanceVanilla {
            get {
                object obj = ResourceManager.GetObject("BalanceVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BalanceVeteran {
            get {
                object obj = ResourceManager.GetObject("BalanceVeteran", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] carolingia {
            get {
                object obj = ResourceManager.GetObject("carolingia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ch_files {
            get {
                object obj = ResourceManager.GetObject("ch_files", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CreatureVanilla {
            get {
                object obj = ResourceManager.GetObject("CreatureVanilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CreatureVeteran {
            get {
                object obj = ResourceManager.GetObject("CreatureVeteran", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] cyrillicchancellor {
            get {
                object obj = ResourceManager.GetObject("cyrillicchancellor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Dark {
            get {
                object obj = ResourceManager.GetObject("Dark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] en_US {
            get {
                object obj = ResourceManager.GetObject("en_US", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] gamesettings {
            get {
                object obj = ResourceManager.GetObject("gamesettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hk_kesf {
            get {
                object obj = ResourceManager.GetObject("hk_kesf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hk_keyb {
            get {
                object obj = ResourceManager.GetObject("hk_keyb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hk_orig {
            get {
                object obj = ResourceManager.GetObject("hk_orig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hk_orsf {
            get {
                object obj = ResourceManager.GetObject("hk_orsf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hk_regr {
            get {
                object obj = ResourceManager.GetObject("hk_regr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hk_setg {
            get {
                object obj = ResourceManager.GetObject("hk_setg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] hotkeys {
            get {
                object obj = ResourceManager.GetObject("hotkeys", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Keyla {
            get {
                object obj = ResourceManager.GetObject("Keyla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] KeylaRegister {
            get {
                object obj = ResourceManager.GetObject("KeylaRegister", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Light {
            get {
                object obj = ResourceManager.GetObject("Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] mk_setg {
            get {
                object obj = ResourceManager.GetObject("mk_setg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ru_RU {
            get {
                object obj = ResourceManager.GetObject("ru_RU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SacredRes2Csv {
            get {
                object obj = ResourceManager.GetObject("SacredRes2Csv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems ... We did not find recognition in Ancaria.
        ///Lily...after all this time? - Always.
        ///Take a horse? A Wood Elf steal a horse? You fool!
        ///Famous last words: &quot;C++ Runtime Error&quot;
        ///Format C: should not be taken literally
        ///No one is missing me ... *cry*
        ///I will return these 500 rubles soon.
        ///Sample Text
        ///Size matters!
        ///ScaredTits
        ///Rule #1: it&apos;s never my fault
        ///In honor of Annika, mistress of the birds.
        ///Random splash!
        ///Get it!
        ///Please, turn on the track nin10doh.
        ///Saints Flow&apos;s good, but Saints Flow with  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string splashes {
            get {
                return ResourceManager.GetString("splashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WPFSharp_Globalizer {
            get {
                object obj = ResourceManager.GetObject("WPFSharp_Globalizer", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
